version: "3.1"
services:
  postgres:
    env_file:
      - backend.env
    build:
      context: db
    ports:
      - "5432:5432"
  backend:
    env_file:
      - backend.env
    build:
      context: .
    ports:
      - "8123:8123"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - APP_PORT=8123
      - APP_MOCKDB=false
      - APP_SPEC=/app/doc
