// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package model

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CommonResponseStatus.
const (
	Error CommonResponseStatus = "error"
	Ok    CommonResponseStatus = "ok"
)

// CommonResponse defines model for CommonResponse.
type CommonResponse struct {
	Message string               `json:"message"`
	Status  CommonResponseStatus `json:"status"`
}

// CommonResponseStatus defines model for CommonResponse.Status.
type CommonResponseStatus string

// Merchant defines model for Merchant.
type Merchant struct {
	Code      string     `json:"code"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        string     `json:"id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// NewMerchant defines model for NewMerchant.
type NewMerchant struct {
	Code string `json:"code"`
}

// NewTeamMember defines model for NewTeamMember.
type NewTeamMember struct {
	Email      string `json:"email"`
	MerchantId string `json:"merchant_id"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Email      string     `json:"email"`
	Id         string     `json:"id"`
	MerchantId string     `json:"merchant_id"`
	UpdatedAt  *time.Time `json:"updated_at,omitempty"`
}

// UpdateMerchant defines model for UpdateMerchant.
type UpdateMerchant struct {
	Code string `json:"code"`
}

// UpdateTeamMember defines model for UpdateTeamMember.
type UpdateTeamMember struct {
	Email string `json:"email"`
}

// PageLimit defines model for PageLimit.
type PageLimit = int

// PageOffset defines model for PageOffset.
type PageOffset = int

// N400Error defines model for 400Error.
type N400Error = CommonResponse

// N404Error defines model for 404Error.
type N404Error = CommonResponse

// N409Error defines model for 409Error.
type N409Error = CommonResponse

// N500Error defines model for 500Error.
type N500Error = CommonResponse

// GetMerchantsParams defines parameters for GetMerchants.
type GetMerchantsParams struct {
	// Limit Limits the number of items on a page.
	Limit *PageLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Specifies the page number of the item to be displayed.
	Offset *PageOffset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetTeammemberByMerchantIdParams defines parameters for GetTeammemberByMerchantId.
type GetTeammemberByMerchantIdParams struct {
	// Limit Limits the number of items on a page.
	Limit *PageLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Specifies the page number of the item to be displayed.
	Offset *PageOffset `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostMerchantsJSONRequestBody defines body for PostMerchants for application/json ContentType.
type PostMerchantsJSONRequestBody = NewMerchant

// PutMerchantByIdJSONRequestBody defines body for PutMerchantById for application/json ContentType.
type PutMerchantByIdJSONRequestBody = UpdateMerchant

// PostTeamMemberJSONRequestBody defines body for PostTeamMember for application/json ContentType.
type PostTeamMemberJSONRequestBody = NewTeamMember

// PutTeammemberByIdJSONRequestBody defines body for PutTeammemberById for application/json ContentType.
type PutTeammemberByIdJSONRequestBody = UpdateTeamMember
